#!/bin/bash

ctd="$( dirname "${BASH_SOURCE[0]}" )"
libdir=$ctd/libs


save_lib() {
	lib=$1
	lname=lib$lib

	if [ -z $lib ] || [ ! -d srclib/$lname ]; then
		echo "$lib library not found."
		return
	fi

	libfiles=$( ls srclib/$lname )

	if [ ! -d "$libdir/$lname" ]; then
		echo "init $lname"
		cwd=$(pwd)
		mkdir "$libdir/$lname"
		cd "$libdir/$lname"
		catest init
		cd "$cwd"
	fi

	mkdir -p "$libdir"/$lname/src
	mkdir -p "$libdir"/$lname/includes
	mkdir -p "$libdir"/$lname/tests

	cp -v srclib/$lname/* "$libdir/$lname/src"

	if [ -d includes/$lib ]; then
		cp -v includes/$lib/* "$libdir/$lname/includes" 
	fi

	headers=$(echo $libfiles | sed -E 's/([a-zA-Z_]*)\.c/includes\/\1\.h/g')
	cp -v $headers "$libdir/$lname/includes"

	ltestdir="$libdir/$lname/tests"
	tests=$(echo $libfiles | sed -E 's/([a-zA-Z_]*)\.c/tests\/test_\1\.c/g')

	for test in $tests; do
		if [ -f "$libdir"/$lname/$test ]; then
			echo "merging $test"
			catest mergetest 
			"$libdir/$lname/$test" $test
		else
			cp -v "$test" "$libdir/$lname/$test"
		fi
	done

	cwd=$(pwd)
	cd "$libdir"/$lname
	catest regenerate
	cd "$cwd"

	echo "$lname saved. Check the ctools repo status for conflicts."

}

copy_tests() {
	lib=$1
	lname=lib$lib
	tocopy="$libdir"/$lname
	echo "Copying $lib tests..."

	tests=$(ls $tocopy/tests)

	for test in $tests; do
		if [ -f tests/$test ]; then
			echo "merging $test"
			catest mergetest tests/$test $tocopy/tests/$test
		else
			cp -v $tocopy/tests/$test tests/$test
		fi
	done

	catest regenerate
}

copy_lib() {
	lib=$1
	lname=lib$lib
	tocopy="$libdir"/$lname

	if [ -z "$lib" ] || [ ! -d "$tocopy" ]; then
		echo "$lib library not found."
		return
	fi

	mkdir -p includes/$lib
	mkdir -p srclib/$lname

	cp -v -r "$tocopy/src/"* srclib/$lname/
	cp -v -r "$tocopy/includes/"* includes/$lib/

	echo "Copy tests?"
	select yn in "Yes" "No"; do
    	case $yn in
    	    Yes ) copy_tests $lib ; break;;
    	    No ) return;;
    	esac
	done
}

case "$1" in
	"save") save_lib $2 ;;
	"copy") copy_lib $2 ;;
	*) echo "Unrecognized command."
		help ;;
esac

